# New Exploratory Analysis (EDA)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [43]:
data_inegi = '../data/raw/inegi/conjunto_de_datos/'

In [102]:
file_path = os.path.join(data_inegi, "atus_anual_2018.csv")
df_prueba = pd.read_csv(file_path, encoding='utf-8', index_col=False, low_memory=False)

In [103]:
df_prueba.head()

COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  ID_DIA  \
0  Municipal           1             1  2018    1       14         45      12   
1  Municipal           1             1  2018    1       14         20      12   
2  Municipal           1             1  2018    1       15         50      12   
3  Municipal           1             1  2018    1       20         15      12   
4  Municipal           1             1  2018    1       12          0       1   

  DIASEMANA                     URBANA  ... PEATMUERTO PEATHERIDO  CICLMUERTO  \
0   Viernes  Accidente en intersección  ...          0          0           0   
1   Viernes  Accidente en intersección  ...          0          0           0   
2   Viernes  Accidente en intersección  ...          0          0           0   
3   Viernes  Accidente en intersección  ...          0          0           0   
4     Lunes  Accidente en intersección  ...          0          0           0   

   CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  NEHERIDO     CLASACC  \
0           0           0           0         0         0    No fatal   
1           0           0           0         0         0  Sólo daños   
2           0           0           0         0         0  Sólo daños   
3           0           0           0         0         0  Sólo daños   
4           0           0           0         0         0  Sólo daños   

              ESTATUS  
0  Cifras Definitivas  
1  Cifras Definitivas  
2  Cifras Definitivas  
3  Cifras Definitivas  
4  Cifras Definitivas  

[5 rows x 45 columns]

In [104]:
df_prueba['ID_ENTIDAD'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [106]:
df_prueba[df_prueba['ID_ENTIDAD']==26].shape

(16369, 45)

In [44]:
anio = [2018, 2019, 2020, 2021, 2022, 2023, 2024] # Change for np.arange(2018, 2025).tolist()
dfs = {}
for dirpath, dirnames, filenames in os.walk(data_inegi):
    for file in filenames:
        file_year = int(file.split('_')[2].split('.')[0])
        if file_year in anio:
            file_path = os.path.join(dirpath, file)
            df_name = f'df_{file_year}'
            dfs[df_name] = pd.read_csv(file_path, encoding='utf-8', low_memory=False)
print(dfs.keys())

dict_keys(['df_2018', 'df_2019', 'df_2020', 'df_2021', 'df_2022', 'df_2023', 'df_2024'])


In [45]:
for key, value in dfs.items():
    columns_len = len(value.columns)
    print(f"{key}: {columns_len}")

df_2018: 45
df_2019: 45
df_2020: 45
df_2021: 45
df_2022: 45
df_2023: 45
df_2024: 45


In [57]:
dfs['df_2018']['ID_ENTIDAD'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119,  95, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [46]:
df_inegi = pd.concat(dfs.values(), ignore_index=True)
print(df_inegi.shape)
display(df_inegi.head())

(2614848, 45)


COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO   ID_DIA  \
0         1           1          2018     1   14       45         12  Viernes   
1         1           1          2018     1   14       20         12  Viernes   
2         1           1          2018     1   15       50         12  Viernes   
3         1           1          2018     1   20       15         12  Viernes   
4         1           1          2018     1   12        0          1    Lunes   

                   DIASEMANA                      URBANA  ... PEATMUERTO  \
0  Accidente en intersección  Sin accidente en esta zona  ...          0   
1  Accidente en intersección  Sin accidente en esta zona  ...          0   
2  Accidente en intersección  Sin accidente en esta zona  ...          0   
3  Accidente en intersección  Sin accidente en esta zona  ...          0   
4  Accidente en intersección  Sin accidente en esta zona  ...          0   

  PEATHERIDO  CICLMUERTO  CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  \
0          0           0           0           0           0         0   
1          0           0           0           0           0         0   
2          0           0           0           0           0         0   
3          0           0           0           0           0         0   
4          0           0           0           0           0         0   

     NEHERIDO             CLASACC  ESTATUS  
0    No fatal  Cifras Definitivas      NaN  
1  Sólo daños  Cifras Definitivas      NaN  
2  Sólo daños  Cifras Definitivas      NaN  
3  Sólo daños  Cifras Definitivas      NaN  
4  Sólo daños  Cifras Definitivas      NaN  

[5 rows x 45 columns]

In [51]:
df_inegi.columns

Index(['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA',
       'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'URBANA', 'SUBURBANA', 'TIPACCID',
       'AUTOMOVIL', 'CAMPASAJ', 'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA',
       'CAMIONETA', 'CAMION', 'TRACTOR', 'FERROCARRI', 'MOTOCICLET',
       'BICICLETA', 'OTROVEHIC', 'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO',
       'CINTURON', 'ID_EDAD', 'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO',
       'PASAHERIDO', 'PEATMUERTO', 'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO',
       'OTROMUERTO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO', 'CLASACC',
       'ESTATUS'],
      dtype='object')

In [53]:
df_inegi['ID_ENTIDAD'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119,  95, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [54]:
df_inegi[df_inegi['ID_ENTIDAD']==570].head()

COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  \
270151        20         570          2018     1    0        0          0   
271018        20         570          2018     2    0        0          0   
271869        20         570          2018     3    0        0          0   
272733        20         570          2018     4    0        0          0   
273638        20         570          2018     5    0        0          0   

                  ID_DIA                   DIASEMANA  \
270151  Certificado cero  Sin accidente en esta zona   
271018  Certificado cero  Sin accidente en esta zona   
271869  Certificado cero  Sin accidente en esta zona   
272733  Certificado cero  Sin accidente en esta zona   
273638  Certificado cero  Sin accidente en esta zona   

                            URBANA  ... PEATMUERTO PEATHERIDO  CICLMUERTO  \
270151  Sin accidente en esta zona  ...          0          0           0   
271018  Sin accidente en esta zona  ...          0          0           0   
271869  Sin accidente en esta zona  ...          0          0           0   
272733  Sin accidente en esta zona  ...          0          0           0   
273638  Sin accidente en esta zona  ...          0          0           0   

        CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO          NEHERIDO  \
270151           0           0           0         0  Certificado cero   
271018           0           0           0         0  Certificado cero   
271869           0           0           0         0  Certificado cero   
272733           0           0           0         0  Certificado cero   
273638           0           0           0         0  Certificado cero   

                   CLASACC  ESTATUS  
270151  Cifras Definitivas      NaN  
271018  Cifras Definitivas      NaN  
271869  Cifras Definitivas      NaN  
272733  Cifras Definitivas      NaN  
273638  Cifras Definitivas      NaN  

[5 rows x 45 columns]